# Makefile Template
CC = gcc # This is your compiler

FLAGS = -Wall # This specifies your flags

SRC = *.c # This is your source files

TARGET = -o program # This is what your executable will be named

all:
	$(CC) $(CFLAGS) $(SRC) $(TARGET)

clean:
	rm -f *.o program
